import { Precedence, PrecedenceEnum } from "../types";

export function getPrecedenceMatrix(): { [key: string]: { [key: string]: Precedence } } {
  // Инициализация матрицы предшествования
  const precedenceMatrix: { [key: string]: { [key: string]: Precedence } } = {
    a: {
      a: PrecedenceEnum.Empty,
      ":=": PrecedenceEnum.Equal,
      ";": PrecedenceEnum.Empty,
      or: PrecedenceEnum.Greater,
      xor: PrecedenceEnum.Greater,
      and: PrecedenceEnum.Greater,
      not: PrecedenceEnum.Empty,
      "(": PrecedenceEnum.Empty,
      ")": PrecedenceEnum.Greater,
      _E: PrecedenceEnum.Empty,
    },
    ":=": {
      a: PrecedenceEnum.Less,
      ":=": PrecedenceEnum.Empty,
      ";": PrecedenceEnum.Equal,
      or: PrecedenceEnum.Less,
      xor: PrecedenceEnum.Less,
      and: PrecedenceEnum.Less,
      not: PrecedenceEnum.Less,
      "(": PrecedenceEnum.Less,
      ")": PrecedenceEnum.Empty,
      _E: PrecedenceEnum.Greater,
    },
    ";": {
      a: PrecedenceEnum.Empty,
      ":=": PrecedenceEnum.Empty,
      ";": PrecedenceEnum.Empty,
      or: PrecedenceEnum.Empty,
      xor: PrecedenceEnum.Empty,
      and: PrecedenceEnum.Empty,
      not: PrecedenceEnum.Empty,
      "(": PrecedenceEnum.Empty,
      ")": PrecedenceEnum.Empty,
      _E: PrecedenceEnum.Greater,
    },
    or: {
      a: PrecedenceEnum.Less,
      ":=": PrecedenceEnum.Empty,
      ";": PrecedenceEnum.Empty,
      or: PrecedenceEnum.Greater,
      xor: PrecedenceEnum.Greater,
      and: PrecedenceEnum.Less,
      not: PrecedenceEnum.Less,
      "(": PrecedenceEnum.Less,
      ")": PrecedenceEnum.Greater,
      _E: PrecedenceEnum.Empty,
    },
    xor: {
      a: PrecedenceEnum.Less,
      ":=": PrecedenceEnum.Empty,
      ";": PrecedenceEnum.Empty,
      or: PrecedenceEnum.Greater,
      xor: PrecedenceEnum.Greater,
      and: PrecedenceEnum.Less,
      not: PrecedenceEnum.Less,
      "(": PrecedenceEnum.Less,
      ")": PrecedenceEnum.Greater,
      _E: PrecedenceEnum.Empty,
    },
    and: {
      a: PrecedenceEnum.Less,
      ":=": PrecedenceEnum.Empty,
      ";": PrecedenceEnum.Empty,
      or: PrecedenceEnum.Greater,
      xor: PrecedenceEnum.Greater,
      and: PrecedenceEnum.Greater,
      not: PrecedenceEnum.Less,
      "(": PrecedenceEnum.Less,
      ")": PrecedenceEnum.Greater,
      _E: PrecedenceEnum.Empty,
    },
    not: {
      a: PrecedenceEnum.Empty,
      ":=": PrecedenceEnum.Empty,
      ";": PrecedenceEnum.Empty,
      or: PrecedenceEnum.Empty,
      xor: PrecedenceEnum.Empty,
      and: PrecedenceEnum.Empty,
      not: PrecedenceEnum.Empty,
      "(": PrecedenceEnum.Equal,
      ")": PrecedenceEnum.Empty,
      _E: PrecedenceEnum.Empty,
    },
    "(": {
      a: PrecedenceEnum.Less,
      ":=": PrecedenceEnum.Empty,
      ";": PrecedenceEnum.Empty,
      or: PrecedenceEnum.Less,
      xor: PrecedenceEnum.Less,
      and: PrecedenceEnum.Less,
      not: PrecedenceEnum.Less,
      "(": PrecedenceEnum.Less,
      ")": PrecedenceEnum.Equal,
      _E: PrecedenceEnum.Empty,
    },
    ")": {
      a: PrecedenceEnum.Empty,
      ":=": PrecedenceEnum.Empty,
      ";": PrecedenceEnum.Empty,
      or: PrecedenceEnum.Greater,
      xor: PrecedenceEnum.Greater,
      and: PrecedenceEnum.Greater,
      not: PrecedenceEnum.Empty,
      "(": PrecedenceEnum.Empty,
      ")": PrecedenceEnum.Greater,
      _E: PrecedenceEnum.Empty,
    },
    _E: {
      a: PrecedenceEnum.Less,
      ":=": PrecedenceEnum.Less,
      ";": PrecedenceEnum.Empty,
      or: PrecedenceEnum.Empty,
      xor: PrecedenceEnum.Empty,
      and: PrecedenceEnum.Empty,
      not: PrecedenceEnum.Empty,
      "(": PrecedenceEnum.Empty,
      ")": PrecedenceEnum.Empty,
      _E: PrecedenceEnum.Empty,
    },
  };

  // Возвращаем инициализированную матрицу предшествования
  return precedenceMatrix;
}
