import { Precedence, PrecedenceEnum } from "./types";

export const precedenceMatrix: { [key: string]: { [key: string]: Precedence } } = {
  a: {
    a: PrecedenceEnum.Equal,
    ":=": PrecedenceEnum.Equal,
    ";": PrecedenceEnum.Empty,
    if: PrecedenceEnum.Less,
    then: PrecedenceEnum.Less,
    else: PrecedenceEnum.Less,
    "<": PrecedenceEnum.Equal,
    ">": PrecedenceEnum.Equal,
    "=": PrecedenceEnum.Equal,
    E: PrecedenceEnum.Less,
  },
  ":=": {
    a: PrecedenceEnum.Equal,
    ":=": PrecedenceEnum.Empty,
    ";": PrecedenceEnum.Empty,
    if: PrecedenceEnum.Empty,
    then: PrecedenceEnum.Less,
    else: PrecedenceEnum.Less,
    "<": PrecedenceEnum.Empty,
    ">": PrecedenceEnum.Empty,
    "=": PrecedenceEnum.Empty,
    E: PrecedenceEnum.Less,
  },
  ";": {
    a: PrecedenceEnum.Greater,
    ":=": PrecedenceEnum.Greater,
    ";": PrecedenceEnum.Empty,
    if: PrecedenceEnum.Empty,
    then: PrecedenceEnum.Greater,
    else: PrecedenceEnum.Greater,
    "<": PrecedenceEnum.Empty,
    ">": PrecedenceEnum.Empty,
    "=": PrecedenceEnum.Empty,
    E: PrecedenceEnum.Less,
  },
  if: {
    a: PrecedenceEnum.Empty,
    ":=": PrecedenceEnum.Empty,
    ";": PrecedenceEnum.Empty,
    if: PrecedenceEnum.Empty,
    then: PrecedenceEnum.Less,
    else: PrecedenceEnum.Less,
    "<": PrecedenceEnum.Empty,
    ">": PrecedenceEnum.Empty,
    "=": PrecedenceEnum.Empty,
    E: PrecedenceEnum.Less,
  },
  then: {
    a: PrecedenceEnum.Greater,
    ":=": PrecedenceEnum.Empty,
    ";": PrecedenceEnum.Empty,
    if: PrecedenceEnum.Equal,
    then: PrecedenceEnum.Empty,
    else: PrecedenceEnum.Empty,
    "<": PrecedenceEnum.Greater,
    ">": PrecedenceEnum.Greater,
    "=": PrecedenceEnum.Greater,
    E: PrecedenceEnum.Empty,
  },
  else: {
    a: PrecedenceEnum.Greater,
    ":=": PrecedenceEnum.Greater,
    ";": PrecedenceEnum.Empty,
    if: PrecedenceEnum.Empty,
    then: PrecedenceEnum.Equal,
    else: PrecedenceEnum.Greater,
    "<": PrecedenceEnum.Empty,
    ">": PrecedenceEnum.Empty,
    "=": PrecedenceEnum.Empty,
    E: PrecedenceEnum.Empty,
  },
  "<": {
    a: PrecedenceEnum.Empty,
    ":=": PrecedenceEnum.Empty,
    ";": PrecedenceEnum.Empty,
    if: PrecedenceEnum.Less,
    then: PrecedenceEnum.Empty,
    else: PrecedenceEnum.Empty,
    "<": PrecedenceEnum.Empty,
    ">": PrecedenceEnum.Empty,
    "=": PrecedenceEnum.Empty,
    E: PrecedenceEnum.Empty,
  },
  ">": {
    a: PrecedenceEnum.Empty,
    ":=": PrecedenceEnum.Empty,
    ";": PrecedenceEnum.Empty,
    if: PrecedenceEnum.Less,
    then: PrecedenceEnum.Empty,
    else: PrecedenceEnum.Empty,
    "<": PrecedenceEnum.Empty,
    ">": PrecedenceEnum.Empty,
    "=": PrecedenceEnum.Empty,
    E: PrecedenceEnum.Empty,
  },
  "=": {
    a: PrecedenceEnum.Empty,
    ":=": PrecedenceEnum.Empty,
    ";": PrecedenceEnum.Empty,
    if: PrecedenceEnum.Less,
    then: PrecedenceEnum.Empty,
    else: PrecedenceEnum.Empty,
    "<": PrecedenceEnum.Empty,
    ">": PrecedenceEnum.Empty,
    "=": PrecedenceEnum.Empty,
    E: PrecedenceEnum.Empty,
  },
  E: {
    a: PrecedenceEnum.Empty,
    ":=": PrecedenceEnum.Empty,
    ";": PrecedenceEnum.Less,
    if: PrecedenceEnum.Empty,
    then: PrecedenceEnum.Empty,
    else: PrecedenceEnum.Empty,
    "<": PrecedenceEnum.Empty,
    ">": PrecedenceEnum.Empty,
    "=": PrecedenceEnum.Empty,
    E: PrecedenceEnum.Empty,
  },
};
